### ISSUE TITLE
Use ueberzugpp instead of chafa?

### ISSUE THREAD

**Issue by megalithic** [justchokingaround/dotfiles#4]
https://github.com/justchokingaround/dotfiles/blob/6a13ddd4e4557a10d1a82bc011c426ddd56367ba/scripts/preview#L38

Hi! I love your preview script; I've been toying around with getting ueberzugpp to get it to render fzf image previews instead of chafa, but am having no luck. Do you have this working in a staged, but un-pushed commit perhaps? :D

Thanks!

**Comment by justchokingaround** [comment]
i did figure out how to get image previews to work in fzf usijg ueberzugpp, however the problem with integrating that into this general preview script is that it takes times for the window to open, and there were also other issues i dont remember. so it's pretty much in an abandonned state atm

**Comment by megalithic** [comment]
Thanks for the response, I'd love to see the semi-working code if you were able to find it. I didn't see it in the commit history.

**Comment by justchokingaround** [comment]
@megalithic i've implemented this in the following commit: https://github.com/justchokingaround/dotfiles/commit/4a1330f49d82c6fd687a96d3edc8fb9d20427e79

this is basically how it looks like:

https://github.com/justchokingaround/dotfiles/assets/44473782/1da75d11-2eb1-49b2-8012-78fbd10a8774

first i show how it looks like with my default preview that i have when i press tab, using `fzf-tab` and then i show how i run it when i press a keybind i set for a wrapper script, mine is on `Alt+i`. the problem with using ueberzugpp by default for fzf's previews is that it creates several files that must be deleted/cleaned up at the end of execution, and there should also be a way to kill the process on exit, which can't really be done with fzf by default, from everything i've gathered. as of now i can't think of a better workaround, this already suits my needs tbh

**Comment by niksingh710** [comment]
@justchokingaround 
tried using the peview script 

getting `ueberzugpp: error while loading shared libraries: libopencv_videoio.so.407: cannot open shar` this error

**Comment by semi710** [comment]
@justchokingaround is there anyway to make the width height and position relative to fzf?

**Comment by justchokingaround** [comment]
for the first comment, try adding this to your ueberzugpp config `~/.config/ueberzugpp/config.json` :
```sh
{
    "layer": {
        "no-opencv":true
    }
}
```

for the second one, there are variables that you can modify in the script:
https://github.com/justchokingaround/dotfiles/blob/main/scripts/preview#L33-L37

**Comment by semi710** [comment]
> for the first comment, try adding this to your ueberzugpp config `~/.config/ueberzugpp/config.json` :
> 
> ```shell
> {
>     "layer": {
>         "no-opencv":true
>     }
> }
> ```
> 
> for the second one, there are variables that you can modify in the script: [`main`/scripts/preview#L33-L37](https://github.com/justchokingaround/dotfiles/blob/main/scripts/preview?rgh-link-date=2023-07-12T19%3A34%3A13Z#L33-L37)

Thanks added changes in lines and got it as expected

```
  ueberzugpp_x="$(($(tput cols) / 2 + 1))"
	ueberzugpp_y="16"
	ueberzugpp_width="$FZF_PREVIEW_COLUMNS"
	ueberzugpp_height="$FZF_PREVIEW_LINES"
	ueberzug_image="wayland"
	image_previewer="ueberuzgpp"
```
