### ISSUE TITLE
What is bard_cookie?

### ISSUE THREAD

**Issue by bydmiller** [justchokingaround/dotfiles#7]
I am 100% sure this is not an issue. In your bard.sh script, you're using an environment variable named bard_cookie. Could you please explain how I can obtain this cookie? I've searched for answers but found a few different suggestions.

Edit: There are two bars (eww & waybar) present, which one  are you using in the pictures on README. 

Thank you.

**Comment by justchokingaround** [comment]
yeah, u can just go to bard's (now gemini) website, open the dev tools, go to the network yab, click on a request and copy the cookie value. that cookie is sensitive data so don't share it with anyone

**Comment by bydmiller** [comment]
Thank you for replying. For some reason i tried using __Secure-3PSID, __Secure-1PSID cookies but it doesn't seem to work for me.

**Comment by justchokingaround** [comment]
i've rewritten my script to use tgpt now kinda
```sh
        main() {
        	${zenity} --progress --text="Waiting for an answer" --pulsate &
        	[ $? -eq 1 ] && exit 1
        	PID=$!
        	answer=$(tgpt -q -w -i "$input")
        	echo "$answer" >/tmp/gpt-answer
        	kill $PID
        	input="$(${zenity} --text="$(printf "%s" "$answer" | sed "s/.\{200\}/&\n/g")" --title="rofi-gpt" --entry)"
        }

        input=$(rofi -dmenu -l 1 -p "  " 2>/dev/null)
        [ -z "$input" ] && exit 1

        while :; do
        	if [ -n "$input" ]; then
        		main "$input"
        	else
        		exit 0
        	fi
        done
```

if u're interested ig. the answers are better than bard in my experience.

https://github.com/aandrew-me/tgpt/

**Comment by bydmiller** [comment]
Thank you. It is really a neat script. 

Fun Fact: I also updated your script to use terminal gpt.
